#!/usr/bin/env bash
set -euo pipefail

running=1

term_handler() {
  echo "I am invincible!!!"
  running=0
}

trap 'term_handler' SIGTERM SIGINT

while [ "$running" -eq 1 ]; do
  echo "To infinity and beyond"
  sleep 2 &
  wait $!
done

echo "Cleanup complete. Bye."
exit 0
