#!/usr/bin/env bash
# Terminate immediately upon SIGTERM.

term_handler() {
  echo "I am invincible!!!"
  exit 0
}

trap 'term_handler' SIGTERM

while true; do
  echo "To infinity and beyond"
  sleep 2
done
