#!/usr/bin/env bash
# Infinite loop that prints a message and responds to SIGTERM without terminating

trap 'echo "I am invincible!!!"' SIGTERM

echo "To infinity and beyond"
while true; do
    sleep 2
    echo "To infinity and beyond"
done
